module.exports = {
  siteTitle: 'GCN',
  siteTitleAlt: 'GCN Gatsby Starter',
  publisher: 'Publisher named GCN',
  siteDescription:
    'A starter template to build amazing static websites with Gatsby, Contentful and Netlify',
  footerAboutText:
    'A starter template to build amazing static websites with Gatsby, Contentful and Netlify',
  siteUrl: 'https://gatsby-japanese-blog.netlify.com',
  postsPerPage: 9,
  pickUpPosts: ['test1', 'test2', 'test3'],
  author: 'GCN User',
  userTwitter: '@twitter',
  shortTitle: 'GCN App',
  shareImage: '/assets/share.jpg',
  shareImageWidth: 900,
  shareImageHeight: 600,
  siteLogo: '/logos/logo-512.png',
  siteIcon: '/logos/logo-512.png',
  backgroundColor: '#e9e9e9',
  themeColor: '#121212',
  copyright: 'Copyright © 2018 GCN User',
  social: {
    twitter: `https://twitter.com/`,
    facebook: `https://www.facebook.com/`,
    instagram: `https://www.instagram.com/`,
    youtube: `https://www.youtube.com/`,
    github: `https://github.com/`,
    rss: `/rss.xml`,
  },
}
