module.exports = {
  siteTitle: 'Gatsby Starter Blog',
  siteTitleAlt: 'Gatsby Starter Blog',
  publisher: 'Publisher named Gatsby Starter Blog',
  siteDescription:
    'A starter template to build amazing static websites with Gatsby, Contentful and Netlify',
  footerAboutText:
    'A starter template to build amazing static websites with Gatsby, Contentful and Netlify',
  siteUrl: 'https://gatsby-starter-blog-contentful.netlify.com/',
  postsPerPage: 9,
  pickUpPosts: ['markdown-cheatsheet', 'sample-post-1', 'sample-post-2'],
  author: 'GSB User',
  userTwitter: '@twitter',
  shortTitle: 'GSB App',
  shareImage: '/assets/share.png',
  shareImageWidth: 1200,
  shareImageHeight: 630,
  siteLogo: '',
  siteIcon: '/logos/logo-512.png',
  backgroundColor: '#000',
  themeColor: '#121212',
  copyright: '© 2019 GSB User',
  social: {
    twitter: `https://twitter.com/`,
    facebook: `https://www.facebook.com/`,
    instagram: `https://www.instagram.com/`,
    youtube: `https://www.youtube.com/`,
    github: `https://github.com/`,
    rss: `/rss.xml`,
  },
}
